### ISSUE TITLE
Extension seems to break fluid json view

### ISSUE THREAD

**Issue by mediaessenz** [pagemachine/cors#9]
Json view of fluid generates no output anymore after installing cors extension.

Take eg. this simple controller code:

```
/**
     * @var string
     */
    protected $defaultViewObjectName = JsonView::class;

    public function getSomethingAction()
    {
        $this->view->assign('value', ["some", "values"]);
    }

```

Normally this should generate a Json like this [{"some","values"}], after installing cors, I get just nothing.

The problem appears only if the call to the action comes from a script embedded in a page.
Calling directly is working.
After deinstalling cors, everything works as expected.

**Comment by mbrodala** [comment]
What HTTP headers do you receive in this case with and without our extension?

**Comment by mediaessenz** [comment]
This is the response header with activated cors:

```
Cache-Control:no-cache, must-revalidate
Cache-Control:max-age=0, no-cache, no-store, must-revalidate
Connection:Keep-Alive
Content-Language:de
Content-Length:0
Content-Type:application/json; charset=utf-8
Date:Tue, 16 Aug 2016 08:56:04 GMT
Expires:0
Expires:Wed, 11 Jan 1984 05:00:00 GMT
Keep-Alive:timeout=5, max=96
Last-Modified:Tue, 16 Aug 2016 08:56:04 GMT
Pragma:no-cache
Pragma:no-cache
Server:Apache/2.4.18 (Debian)
```

This is the corresponding status code:

```
Status Code:204 No Content
```

If I deactivate cors, I get this response head:

```
Cache-Control:max-age=0, no-cache, no-store, must-revalidate
Cache-Control:no-cache, must-revalidate
Connection:Keep-Alive
Content-Language:de
Content-Type:application/json; charset=utf-8
Date:Tue, 16 Aug 2016 09:02:05 GMT
Expires:Wed, 11 Jan 1984 05:00:00 GMT
Expires:0
Keep-Alive:timeout=5, max=92
Last-Modified:Tue, 16 Aug 2016 09:02:05 GMT
Pragma:no-cache
Pragma:no-cache
Server:Apache/2.4.18 (Debian)
Transfer-Encoding:chunked
```

together with this status code:

```
Status Code:200 OK
```

FYI: I use the extension typoscript_rendering from helmut hummel to call the action.

**Comment by mbrodala** [comment]
The status code 204 is only sent in case a cross origin request was performed and denied.

Can you also post your request headers?

I'll add some logging to the extension.

**Comment by mbrodala** [comment]
I just released version [2.0.1](https://github.com/pagemachine/cors/releases/tag/2.0.1) which includes some logging. Could you check your `typo3temp/logs/typo3*.log` for messages?

**Comment by mediaessenz** [comment]
After updating to 2.0.1 the action call throws an execption:
`Argument 2 passed to TYPO3\CMS\Core\Log\Logger::error() must be of the type array, object given, called in /app/web/typo3conf/ext/cors/Classes/Hooks/ContentPostProcessorHook.php on line 105`

But if I xdebug the object stored in $e I get this:
<img width="1622" alt="bildschirmfoto 2016-08-16 um 12 49 26" src="https://cloud.githubusercontent.com/assets/16038153/17696630/f0ee0e94-63af-11e6-88e0-349603b40b5e.png">

To set the allowOrigin I use this condition:

```
[applicationContext = Development*]
    config {
        cors {
            allowOrigin = *
        }
    }
[end]
```

**Comment by mbrodala** [comment]
Sorry about the error, version [2.0.2](https://github.com/pagemachine/cors/releases/tag/2.0.2) fixes this.

**Comment by mediaessenz** [comment]
Here it the result from the logs file:

```
Tue, 16 Aug 2016 13:11:10 +0200 [ERROR] request="b6541dab317ee" component="PAGEmachine.Cors.Hooks.ContentPostProcessorHook": Error processing CORS request: Access not allowed for origin "https://www.jugend-debattiert.de.vm" - {"exception":"PAGEmachine\\Cors\\AccessControl\\Exception\\AccessDeniedException: Access not allowed for origin \"https:\/\/www.jugend-debattiert.de.vm\" in \/app\/web\/typo3conf\/ext\/cors\/Classes\/AccessControl\/Negotiator.php:233\nStack trace:\n#0 \/app\/web\/typo3conf\/ext\/cors\/Classes\/Hooks\/ContentPostProcessorHook.php(102): PAGEmachine\\Cors\\AccessControl\\Negotiator->processRequest(Object(PAGEmachine\\Cors\\AccessControl\\Request), Object(PAGEmachine\\Cors\\AccessControl\\Response))\n#1 [internal function]: PAGEmachine\\Cors\\Hooks\\ContentPostProcessorHook->process(Array, Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))\n#2 \/app\/vendor\/typo3\/cms\/typo3\/sysext\/core\/Classes\/Utility\/GeneralUtility.php(4375): call_user_func_array(Array, Array)\n#3 \/app\/vendor\/typo3\/cms\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3735): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction('PAGEmachine\\\\Cor...', Array, Object(TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController))\n#4 \/app\/vendor\/typo3\/cms\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(240): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->processOutput()\n#5 \/app\/vendor\/typo3\/cms\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#6 \/app\/vendor\/typo3\/cms\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#7 \/app\/vendor\/typo3\/cms\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#8 \/app\/vendor\/typo3\/cms\/index.php(34): {closure}()\n#9 {main}"}
```

**Comment by mbrodala** [comment]
Alright now we gotta check the request headers and especially the origin. On which host is the script located which performs the AJAX request?

**Comment by mbrodala** [comment]
After some quick exchange via Slack we found out that the request is sent with cookies. Such requests cannot be allowed with the wildcard, thus the specific origin must be set explicitly:

```
[applicationContext = Development*]
    config {
        cors {
            allowOrigin = https://www.jugend-debattiert.de.vm
        }
    }
[end]
```

As mentioned in the README, multiple origins are also perfectly fine:

```
[applicationContext = Development*]
    config {
        cors {
            allowOrigin = https://www.jugend-debattiert.de.vm, http://example.org
        }
    }
[end]
```
